git clone git@github.com:ballerina-platform/module-ballerina-socket.git
git clone git@github.com:ballerina-platform/module-ballerina-auth.git
git clone git@github.com:ballerina-platform/module-ballerina-email.git
git clone git@github.com:ballerina-platform/module-ballerina-grpc.git
git clone git@github.com:ballerina-platform/module-ballerina-http.git
git clone git@github.com:ballerina-platform/module-ballerina-ldap.git
git clone git@github.com:ballerina-platform/module-ballerinax-kafka.git
git clone git@github.com:ballerina-platform/module-ballerinax-nats.git
git clone git@github.com:ballerina-platform/module-ballerinax-rabbitmq.git
git clone git@github.com:ballerina-platform/module-ballerina-oauth2.git
git clone git@github.com:ballerina-platform/module-ballerina-websub.git
git clone git@github.com:ballerina-platform/module-ballerina-jwt.git
git clone git@github.com:ballerina-platform/module-ballerina-mime.git
git clone git@github.com:ballerina-platform/module-ballerina-sql.git
git clone git@github.com:ballerina-platform/module-ballerina-java.jdbc.git
git clone git@github.com:ballerina-platform/module-ballerinax-mysql.git
git clone git@github.com:ballerina-platform/module-ballerina-io.git
git clone git@github.com:ballerina-platform/module-ballerina-cache.git
git clone git@github.com:ballerina-platform/module-ballerina-config.git
git clone git@github.com:ballerina-platform/module-ballerina-crypto.git
git clone git@github.com:ballerina-platform/module-ballerina-file.git
git clone git@github.com:ballerina-platform/module-ballerina-filepath.git
git clone git@github.com:ballerina-platform/module-ballerina-java.arrays.git
git clone git@github.com:ballerina-platform/module-ballerina-jsonutils.git
git clone git@github.com:ballerina-platform/module-ballerina-log.git
git clone git@github.com:ballerina-platform/module-ballerina-math.git
git clone git@github.com:ballerina-platform/module-ballerina-reflect.git
git clone git@github.com:ballerina-platform/module-ballerina-runtime.git
git clone git@github.com:ballerina-platform/module-ballerina-stringutils.git
git clone git@github.com:ballerina-platform/module-ballerina-system.git
git clone git@github.com:ballerina-platform/module-ballerina-task.git
git clone git@github.com:ballerina-platform/module-ballerina-time.git
git clone git@github.com:ballerina-platform/module-ballerina-xmlutils.git
git clone git@github.com:ballerina-platform/module-ballerina-xslt.git
git clone git@github.com:ballerina-platform/module-ballerina-encoding.git
